### ISSUE TITLE
Your Info - Form accepts invalid inputs

### ISSUE THREAD

**Issue by cessalvarez** [tooldigital/pandora-sly-p2#13]
When the user enters email address like " -----@gmail.com", the button enables. Also, First and Last Name text field accepts invalid characters like numeric/ special characters and even blank spaces.

**Expected Result:**

- The button should remain disabled if there's an invalid input entered on any field.

**Browser / Device info:**
- All desktop browsers.

**URL:**
- http://soundslikeyoudev.seethroughlab.com/

**Steps:**

1. Load the URL.
2. Enter characters aside from the required input.
3. Verify that the button is enabled. The input is accepted as valid.

**See the following video:**

- https://drive.google.com/open?id=1Kxtie9WDVJHouOempg28x2dxU3pIbc0B

**Comment by wearenocomputer** [comment]
Following rules for field-validation apply:
- email needs to be of format x@x.xxx
- name only accepts letter, numbers, spaces and '.' (eg James-Earl Sr.)

Proposing to close because:
- email validation is identical to v1
- in v1 there was no validation on names
- don't recall any sever edge-case issues with this causing problems

@jeankcha 
Please advice...

**Comment by jeankcha** [comment]
Agreed. Closing.
