### ISSUE TITLE
Mobile | Landscape | Overlapping Contents

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#8]
When the device is turned into landscape orientation notice that there are some contents which overlap with each other. 

Note: Below are the sections which have overlapping issues.
- home
- your info -  only overlaps when on-screen keyboard is active.
- your mood
- your songs
- your custom songs
- your summary

**Expected Result:**
- Assets should be optimized especially on landscape mode

**Browser / Device info:**
- iPhone 7+ (11.3) - Safari, Chrome 67
- Galaxy S6 (6.0)   - Native 6.4.10.5
- Pixel XL (7.1.2)  - Chrome 66

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-custom-song

**Steps:**
1. Load the URL.
2. Verify that the following sections above have overlapping contents.

Please see the attached screenshot(s):  https://goo.gl/5xic91

**Comment by wearenocomputer** [comment]
This is going to be tough... since we: 
- A) Have a lot of content we want to display
- B) The experience is designed to be used in portrait mode

When viewed on smartphones there will always be content which is overlapping and/or not visible (unless people start scrolling). This is something we can not fix in the browser, but rather a content/UX/design issue.

In order to get it right for use in landscape mode, we'd need to change design/UX (to fit on landscape) and implement the new/updated design in development (just to give a clear view on ramifications). Most people use their phones in portrait mode, unless when watching video or playing games.

Question is how big an issue is this, knowing that we'd need to:
- rework design/ux
- implement & test in development
- for about 1% of all use-cases on smartphones

We've have done our best to make this work/fit as many screens as possible.
Please advice...

**Comment by jeankcha** [comment]
This is an edge case scenario, so we won't be reworking design or UX for this landscape issue.
